### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [orbsini/f1-3-c2p1-colmar-academy#2]
Overall Excellent.  I really didn't see any major flaws or errors in this project.  Everything was well commented, organized, and readable.  

I did mention the mobile view because I don't know if it is your intention or not to be like that at a tablet size break point.  Either way it isn't a flaw.

Now lets talk about the future of web development, as a final challenge I like you to look into PWAS(progressive web apps). https://developers.google.com/web/fundamentals/getting-started/codelabs/your-first-pwapp/

PWA is a way to make your website look and feel like an app when being used on a phone(Apple is starting to support this right now this is more android). See if you can convert this site to a PWA as this seems to be the next big trend.

**Comment by orbsini** [comment]
Thanks Farish! 
PWAS: Awesome. I'll definitely check this out!
Take care, friend.
